# Generated by Django 2.2.16 on 2022-04-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220407_0328'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_unique_relationships',
        ),
    ]
